spring.application.name=gift-together

spring.datasource.url=jdbc:postgresql://localhost:5432/gift_together
spring.datasource.username=piwoori
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false